{{- if .Values.httpPort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    type: {{ .Values.type | default "service" }}
{{- if $.Values.labels }}
{{ toYaml $.Values.labels | indent 4 }}
{{- end }}
{{- template "chart.shipcatRefs" . }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.httpPort }}
    protocol: TCP
    name: http
  - port: 8080
    protocol: TCP
    name: health
{{- range $p := .Values.ports }}
  - port: {{ $p.port }}
    protocol: {{ $p.protocol }}
    name: {{ $p.name }}
{{- end }}
  selector:
    app: {{ .Values.name }}
{{- end }}
